config/routes.rb
Rails.application.routes.draw do

  get 'welcome/index'

  devise_for :users, controllers: { registrations: "registrations" }

  resources :projects do
    resources :tickets
  end
  
  get '/projects/:id/new_associate', to: 'projects#new_associate'
  get 'index_tickets', to: 'projects#index_tickets'
  get '/projects/:id/quit', to: 'projects#quit'
  patch '/projects/:id/invite', to: 'projects#invite'
  patch '/projects/:id/change_owner', to: 'projects#change_owner'
  patch '/projects/:id/force_quit', to: 'projects#force_quit'
  
  

   root 'welcome#index'

end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
  belongs_to :project
  belongs_to :user
  has_attached_file :attachment, styles: { small: "64x64", med: "100x100", large: "200x200" }, :default_url => "/missing_resource.txt"
  validates_attachment_content_type :attachment, :content_type => [
    
    "image/jpg",
    "image/jpeg",
    "image/png",
    "image/gif",
    "application/vnd.ms-excel",
    "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
    "application/msword",
    "application/vnd.openxmlformats-officedocument.wordprocessingml.document", 
    "text/plain" 
  ]
  
  validates :title, presence: true
  validates :description, presence: true
  validates :priority, presence: true
  
  enum status: [:open, :closed, :cancelled,]
  
  def delete_attachment
    self.attachment.destroy
    self.attachment.clear
    self.attachment_name = nil;
  end
  
  def attach
    if(self.attachment.exists?)
      @attach = "1"
    else
      @attach = "0"
    end
  end


  
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
    
    before_filter :check_if_developer
    
    def index
        @statuses = Ticket.statuses
        @project = Project.find(params[:project_id])
        @tickets = @project.tickets

    end
    
    def show
        @statuses = Ticket.statuses
        @project = Project.find(params[:project_id])
        @ticket = @project.tickets.find(params[:id])
        
        if @ticket.user_id == current_user.email
            @ticket.update_attributes(:reported => true)
        end
        
    end
    
    def new
        @statuses = Ticket.statuses
        @project = Project.find(params[:project_id])
        @ticket = Ticket.new
        
    end
    
    def create
        @statuses = Ticket.statuses
        @project = Project.find(params[:project_id])
        @ticket = @project.tickets.create(ticket_params)
        
        unless params[:ticket][:attachment] != nil
          @ticket.attachment_name = nil
        end
        
        if @ticket.save
            redirect_to  project_ticket_path(:project_id => @project.id ,:id => @ticket.id)
        else 
            render 'new'
        end
        @ticket.update_attributes(:reported => false)

        
    end
    
    def edit
        @statuses = Ticket.statuses
        @project = Project.find(params[:project_id])
        @ticket = @project.tickets.find(params[:id])
        
    end
    
    def update
        @statuses = Ticket.statuses
        @project = Project.find(params[:project_id])
        @ticket = @project.tickets.find(params[:id])
        
        unless params[:ticket][:user_id]==nil or @ticket.user_id == params[:ticket][:user_id]
            params[:ticket][:reported] = false
        end
        
        unless params[:ticket][:attach]=="1"
            @ticket.delete_attachment
            params[:ticket][:attachment_name] = nil 
        else
            unless @ticket.attachment.exists? or params[:ticket][:attachment] != nil
               params[:ticket][:attachment_name] = nil 
            end
        end
        
        if @ticket.update(ticket_params)
            redirect_to project_ticket_path(:id => @ticket.id)
        else 
            render 'edit'
        end


    end
    
    def destroy
        @project = Project.find(params[:project_id])
        @ticket = @project.tickets.find(params[:id])
        @ticket.destroy
        redirect_to  project_tickets_path
        
    end
    
    
    private
        def ticket_params
            params.require(:ticket).permit(:title, :description, :priority, :estimation, :status, :attachment, :attachment_name, :user_id, :reported)
        end
        
        def check_if_developer
            @project = Project.find(params[:project_id])
            unless @project.users.include?(current_user)
                redirect_to project_path(params[:project_id])
            end
        end
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/tickets/_form.html.erb
<%= form_for [@project, @ticket], :html => { :multipart => true } do |f| %>

  <%= javascript_tag do %>
  $(document).ready(function(){
  
    if(!$("#ticket_attach").is(':checked') ) {
      $("#attachment-form").hide();
    }
  
    $("#ticket_attach").click(function(){
          if(this.checked) {
            $("#attachment-form").show();
          } else {
            $("#attachment-form").hide();
          }
    });
  });

  <% end %>
  
  <% if @ticket.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@ticket.errors.count, "error") %>
      </h2>
      <ul>
        <% @ticket.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title, class: "form-control" %>
  </p>
 
  <p>
    <%= f.label :description %><br>
    <%= f.text_area :description,class: "form-control", rows:3; %>
  </p>
 
  <p>
    <%= f.label :priority %><br>
    <%= f.number_field :priority,class: "form-control" %>
  </p>
  
  <p>
    <%= f.label :estimation %><br>
    <%= f.number_field :estimation,class: "form-control" %>
  </p>
  
  </p>
    <%= f.label 'Assigned to' %><br>
    <%= f.select :user_id, options_for_select(@project.users.map do |u| [u.get_description, u.email] end, @ticket.user_id), {include_blank: true} %>
  </p>
  
  <p>
    
    <label>
    <%= f.check_box :attach %>
    <%= f.label :attach, 'Attachment' %>
    </label>
    
    <div id="attachment-form" class="well">
      <p>
        <%= f.label :attachment_name %><br>
        <%= f.text_field :attachment_name, class: "form-control" %>
      </p>
      <p>

        <%= f.file_field :attachment%>
      </p>
    </div>
  </p>
  


  <p>
    <%= f.select :status, options_for_select(Ticket.statuses.keys, @ticket.status) %>
  </p>
  

  
    <p>
      <%= f.submit class: "btn btn-default", role: "button" %>
    </p>
  
<% end %>

app/views/tickets/index.html.erb
<div class="page-header">
    <h1> <%= @project.name %> <small>Tickets</small></h1>
</div>

<% def display_ticekt(ticket) %>
    <% if ticket.reported==false %>
            <tr data-href= <%= project_ticket_path(:id => ticket.id, :project_id => ticket.project) %>>
    <% else %>
            <tr data-href= <%= project_ticket_path(:id => ticket.id, :project_id => ticket.project) %>>
    <% end %>
            <td>
                <strong><%= ticket.title %></strong>
            </td>
            <td>
                <%= ticket.description %>
            </td>
            <td>
                <%= ticket.priority %>
            </td>
            <td>
                <%= ticket.estimation %>
            </td>
            <td>
                <%= User.where(:email => ticket.user_id).first.get_description %>
            </td>
            <td>
                <%= ticket.status %>
            </td>

        </tr>
<% end %>

<div class="table-responsive">
    <table class="table">
        <thead>
            <tr>
                <th>Title</th>
                <th>Description</th>
                <th>Priority</th>
                <th>Estimation</th>
                <th>Assigned to</th>
                <th>Status</th>
            </tr>
        </thead>
        
       
    <% @tickets.each do |ticket| %>
        <% display_ticekt(ticket) %>
    <% end %>
</div>
</table>

<p>
    <%= link_to 'New ticket', new_project_ticket_path, class: "btn btn-default", role: "button" %>
</p>

<p>
    <%= link_to 'Back', @project, class: "btn btn-primary", role: "button"  %>
</p>
  
<%= javascript_tag do %>
      
    $(function(){
        $('.table tr[data-href]').each(function(){
            $(this).css('cursor','pointer').hover(
                function(){ 
                    $(this).addClass('active'); 
                },  
                function(){ 
                    $(this).removeClass('active'); 
                }).click( function(){ 
                    document.location = $(this).attr('data-href'); 
                }
            );
        });
    });

<% end %>

app/views/tickets/new.html.erb
<%= render 'form' %>

app/views/tickets/show.html.erb
<div class="page-header">
  <h1> <%= @ticket.title %></h1>
</div>
<p>
  <strong>Description:</strong>
  <%= @ticket.description %>
</p>
<p>
  <strong>Priority:</strong>
  <%= @ticket.priority %>
</p>
<p>
  <strong>Estimation:</strong>
  <%= @ticket.estimation %>
</p>

<p>
  <strong>Assigned to:</strong>
  <% if @ticket.user_id != '' %>
      <%= User.where(:email => @ticket.user_id).first.get_description %>
  <% else %>
      <%= "Not assigned" %>
  <% end %>
</p>

<p>
  <strong>Status:</strong>
  <%= @ticket.status %>
</p>

<% if @ticket.attachment.exists? %>
    <p>
        <strong>Attachment:</strong>
        <% if @ticket.attachment_name.squeeze=='' %>
            <%= link_to "attached file", @ticket.attachment.url(:original, false) %>
        <% else %>
            <%= link_to @ticket.attachment_name, @ticket.attachment.url(:original, false) %>
        <% end %>
    </p>
<% end %>



<p>
    <%= link_to 'Edit', edit_project_ticket_path(:project_id => @project.id ,:id => @ticket.id), class: "btn btn-default", role: "button"  %>
</p>

<p>
      <button type="button" class="btn btn-default" data-toggle="modal" data-target="#deleteTicket">Delete ticket</button>
</p>

<p>
    <%= link_to 'Back', project_tickets_path, class: "btn btn-primary", role: "button" %>
</p>



<div id="deleteTicket" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <div class="modal-content">
      <div class="modal-header">
        <h3>Are you sure that you want to delete this ticket?</h3>
      </div>
      <div class="modal-body">
          Click confirm to proceed
          
      </div>
      <div class="modal-footer">
        <%= link_to "Confirm", project_ticket_path(:project_id => @project.id ,:id => @ticket.id), method: :delete, class: "btn btn-default", role: "button", id:"delete_button" %>
        <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
      </div>
    </div> 

  </div>
</div>