config/routes.rb
Rails.application.routes.draw do

  get 'welcome/index'

  devise_for :users, controllers: { registrations: "registrations" }

  resources :projects do
    resources :tickets
  end
  
  get '/projects/:id/new_associate', to: 'projects#new_associate'
  get 'index_tickets', to: 'projects#index_tickets'
  get '/projects/:id/quit', to: 'projects#quit'
  patch '/projects/:id/invite', to: 'projects#invite'
  patch '/projects/:id/change_owner', to: 'projects#change_owner'
  patch '/projects/:id/force_quit', to: 'projects#force_quit'
  
  

   root 'welcome#index'

end

app/models/project.rb
class Project < ActiveRecord::Base
    has_many :tickets, dependent: :destroy
    has_and_belongs_to_many :users
    belongs_to :owner, :class_name => 'User', :foreign_key => 'owner_id'
    
    validates :name, presence: true
    
    def set_owner(user)
        if self.users.include?(user)
            self.owner = user
        end
    end
    
    def add_associate(user)
        unless self.users.include?(user) or user == nil
            self.users << user
        end
    end
    
    def remove_associate(user)
        unless user == owner
            self.users.delete(user)
        end
    end
    
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  
  def index
    if params[:private] == "true"
      @projects = current_user.projects.paginate(:page => params[:page], :per_page => 10)
      
    else
      @projects = Project.paginate(:page => params[:page], :per_page => 10)
    end
    
  end


  def show
    @project = Project.find(params[:id])
    
  end

  def new
     @project = Project.new
  end
  
  def edit 
    if check_if_owner
      @project = Project.find(params[:id])
    else
      redirect_to @project
    end
    
  end
  
  def update
    @project = Project.find(params[:id])
    
    if @project.update(project_params)
      redirect_to @project
    else
      render 'edit'
    end
    
  end
  

  def create
    @project = Project.new(project_params)
    @project.add_associate current_user
    @project.set_owner current_user
    
    if @project.save
      redirect_to @project
    else
      render 'new'
    end
    
  end

  def destroy
    
    if check_if_owner
      @project = Project.find(params[:id])
      @project.destroy
      redirect_to projects_path
    else
      redirect_to @project
    end
  end

  
  def change_owner
    if check_if_owner
      @project = Project.find(params[:id])
      unless (params[:project][:owner_id]) == nil
        @project.update(project_params)
      end
      redirect_to @project
    else
      redirect_to @project
    end
  end
  
  def new_associate
    if check_if_owner
      @project = Project.find(params[:id])
    end
  end
  
  
  def invite
    @project = Project.find(params[:id])
    if check_if_owner
      @user = User.where(:email => params[:email]).first
      @project.add_associate(@user)
      redirect_to @project
    else
      redirect_to @project
    end
  end
  
  
  def quit
    @project = Project.find(params[:id])
    @project.remove_associate current_user
    
    @project.tickets.each { |t|
      if t.user_id == current_user.email
        t.update_attributes(:user_id => nil)
      end
    }
    
    @project.update_attributes(:users => @project.users)
    redirect_to projects_path
    
  end
  
  def force_quit
    if check_if_owner
      @project = Project.find(params[:id])
      @user = User.find(params[:project][:users])
      @project.remove_associate @user
      
      @project.tickets.each { |t|
        if t.user_id == @user.email
          t.update_attributes(:user_id => nil)
        end
      }
      
      @project.update_attributes(:users => @project.users)
      redirect_to @project
    else
      redirect_to @project
    end
    
  end
  
  
  def index_tickets
    @statuses = Ticket.statuses
    @tickets = Ticket.where(:user_id => current_user.email)
  end



  private
    def project_params
      params.require(:project).permit(:name, :description, :owner_id)
    end
    
    
    def check_if_owner
      @project = Project.find(params[:id])
      unless @project.owner == current_user
        false
      else
        true
      end
      
    end


  
end

app/helpers/projects_helper.rb
module ProjectsHelper
    def resource_name
        :user
    end
    
    def resource
        @resource ||= User.new
    end
    
    def devise_mapping
        @devise_mapping ||= Devise.mappings[:user]
    end
    
end

app/views/projects/_form.html.erb
<%= form_for @project do |f| %>
  
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@project.errors.count, "error") %>
      </h2>
      <ul>
        <% @project.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


    <p>
      <%= f.label :name %><br>
      <%= f.text_field :name, class:"form-control" %>
    </p>
   
    <p>
      <%= f.label :description %><br>
      <%= f.text_area :description, class:"form-control", rows:"8"  %>
    </p>
   
    <p>
      <%= f.submit class: "btn btn-default", role: "button" %>
    </p>
    
    <p>
        <%= link_to 'Back', :back, class: "btn btn-primary", role: "button" %>
    </p>
      
  
<% end %>

app/views/projects/edit.html.erb
<%= render 'form' %>

app/views/projects/index.html.erb
<div class="page-header">
  <% if params[:private] == "true" %>
    <h1> Browse <small>My projects</small></h1>
  <% else %>
    <h1> Browse <small>All projects</small></h1>
  <% end %>
  
</div>
<div class="table-responsive">
  <table class="table table-hover">
    
    <thead>
      <tr>
        <th>Project name</th>
        <th>Description</th>
      </tr>
    </thead>
   
    <tbody>
      <% @projects.each do |project| %>
        <tr data-href= <%= project_path(project) %>>
          
          <td style="width:12%"><%= project.name %></td>
          <td><%= project.description %></td>
        </tr>
      <% end %>
    </tbody>
    
    
  </table>
</div>


<div style="text-align: left;"><%= will_paginate @posts, renderer: BootstrapPagination::Rails, class: 'pagination-sm' %></div>

<p>
    <%= link_to 'New project', new_project_path, class: "btn btn-primary", role: "button" %>
</p>



<%= javascript_tag do %>
      
    $(function(){
        $('.table tr[data-href]').each(function(){
            $(this).css('cursor','pointer').hover(
                function(){ 
                    $(this).addClass('active'); 
                },  
                function(){ 
                    $(this).removeClass('active'); 
                }).click( function(){ 
                    document.location = $(this).attr('data-href'); 
                }
            );
        });
    });

<% end %>

app/views/projects/index_tickets.html.erb
<div class="page-header">
  <h1> My tickets</h1>
</div>

<% def display_ticekt(ticket) %>

        <tr data-href= <%= project_ticket_path(:id => ticket.id, :project_id => ticket.project) %>>
            <td>
                <strong><%= ticket.project.name %></strong>
            </td>
            <td>
                <span style="white-space: nowrap;">
                    <%= ticket.title %>
                    <% if ticket.reported==false %>
                        <span class="label label-default">New</span>
                    <% end %>
                </span>
            </td>
            <td>
                <%= ticket.description %>
            </td>

        </tr>
<% end %>

<div class="table-responsive">
    <table class="table">
        <thead>
            <tr>
                <th>Project</th>
                <th>Title</th>
                <th>Description</th>
            </tr>
        </thead>
        
       
    <% @tickets.select { |t| t.reported==false }.each do |ticket| %>
        <% display_ticekt(ticket) %>
    <% end %>
    
    <% @tickets.select { |t| t.reported==true and t.status=="open" }.each do |ticket| %>
        <% display_ticekt(ticket) %>
    <% end %>
    
    <% @tickets.select { |t|  t.reported==true and t.status=="closed" }.each do |ticket| %>
        <% display_ticekt(ticket) %>
    <% end %>
    
    
    </table>
</div>
  
<%= javascript_tag do %>
      
    $(function(){
        $('.table tr[data-href]').each(function(){
            $(this).css('cursor','pointer').hover(
                function(){ 
                    $(this).addClass('active'); 
                },  
                function(){ 
                    $(this).removeClass('active'); 
                }).click( function(){ 
                    document.location = $(this).attr('data-href'); 
                }
            );
        });
    });

<% end %>

app/views/projects/new.html.erb
<%= render 'form' %>

app/views/projects/new_associate.html.erb
<%= render 'users/registrations/register' %>

app/views/projects/show.html.erb
      <div style="float:right;">
        <% if @project.owner == current_user %>

            <div class="dropdown" style="display:inline-block;">
              <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-expanded="true">
                Manage developers
                <span class="caret"></span>
              </button>
              <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu1">
                <li role="presentation"><a role="menuitem" tabindex="-1" data-toggle="modal" data-target="#changeOwner" style="cursor:pointer;">Change owner</a></li>
                <li role="presentation"><%= link_to 'New developer account', {:action => :new_associate}, role: "menuitem" %></li>
                <li role="presentation"><a role="menuitem" tabindex="-1" data-toggle="modal" data-target="#invite" style="cursor:pointer;">Invite developer</a></li>
                <li role="presentation"><a role="menuitem" tabindex="-1" data-toggle="modal" data-target="#forceQuit" style="cursor:pointer;">Remove developer</a></li>
              </ul>
            </div>

            <%= link_to 'Edit project', edit_project_path(@project), class: "btn btn-default", role: "button"  %>

            <button type="button" class="btn btn-default" data-toggle="modal" data-target="#deleteProject">Delete project</button>

          
            <% end %>
            <% if @project.users.include?(current_user) %>
            <% unless @project.owner == current_user %>
                  <button type="button" class="btn btn-default" data-toggle="modal" data-target="#quitProject">Quit project</button>
            <% end %>

         <% end %>
      </div>


  
        <div class="page-header">
          <h1> <%= @project.name %></h1>
        </div>
        
        <p>
          <strong>Description:</strong>
          <%= @project.description %>
        </p>
        
        
          <div class="panel panel-default">
            <div class="panel-heading"><strong>Developers:</strong></div>
            <div class="panel-body">
        
            <ul style="list-style-type: circle; padding-left:10px;">
          
            <% @project.users.each do |u| %>
              <li>
                <%= u.get_description %>
                  <% if u==@project.owner %>
                    <strong>(Project owner)</strong>
                  <% end %>
                </li>
          
            <% end %>
            </ul>
          </div>
        </div>
        <% if @project.users.include?(current_user) %>
          <p>
              <%= link_to 'Tickets', [@project, :tickets], class: "btn btn-lg btn-primary", role: "button"  %>
          </p>
        <% end %>






















<div id="deleteProject" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <div class="modal-content">
      <div class="modal-header">
        <h3>Are you sure that you want to delete this project?</h3>
      </div>
      <div class="modal-body">
        <p>Type "delete" in following form and click "Delete project" to proceed</p>
        <%= text_field_tag "delete_confirm", '', class:"form-control" %>
      </div>
      <div class="modal-footer">
        <%= link_to "Delete project", project_path(@project), method: :delete, class: "btn btn-default", role: "button", id:"delete_button" %>
        <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
      </div>
    </div> 

  </div>
</div>


<div id="quitProject" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <div class="modal-content">
      <div class="modal-header">
        <h3>Quit project</h3>
      </div>
      <div class="modal-body">
        Are you sure that you want to quit project?<br>

      </div>
      <div class="modal-footer">
        <%= link_to "Quit", {:action => :quit}, class: "btn btn-default", role: "button" %>
        <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
      </div>
    </div>

  </div>
</div>



<div id="forceQuit" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <div class="modal-content">
      
      <%= form_for @project, url: {action: "force_quit"} do |f| %>
      <div class="modal-header">
        <h3>Choose a user to be removed from developers list</h3>
      </div>
      <div class="modal-body">
          <p>
            <%= f.select :users, options_for_select((@project.users.select{|u| u != current_user}).map do |u| [u.get_description, u.id] end) %>
          </p>
      </div>
      
      <div class="modal-footer">
          
          <%= f.submit "Confirm", class: "btn btn-default", role: "button" %>
          <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
      </div>
      <% end %>
      
    </div>

  </div>
</div>



<div id="changeOwner" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <div class="modal-content">
      
      <%= form_for @project, url: {action: "change_owner"} do |f| %>
      <div class="modal-header">
        <h3>Choose new project owner</h3>
      </div>
      <div class="modal-body">
        
          <p>
            <%= f.select :owner_id, options_for_select(@project.users.map do |u| [u.get_description, u.id] end, current_user.id) %>
          </p>
          <p>
            * note that you will no longer have owner privileges in this project
          </p>
      </div>
      <div class="modal-footer">
          
          <%= f.submit "Confirm", class: "btn btn-default", role: "button" %>
          <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
      </div>
      <% end %>
      
    </div>

  </div>
</div>


<div id="invite" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <div class="modal-content">
      
      <%= form_for @project, url: {action: "invite"} do |f| %>
      <div class="modal-header">
        <h3>Type e-mail address</h3>
      </div>
      <div class="modal-body">
          <p>
            <%= email_field_tag 'email', "", class:"form-control" %>
          </p>
      </div>
      <div class="modal-footer">
          
          <%= f.submit "Confirm", class: "btn btn-default", role: "button" %>
          <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
          
      </div>
      <% end %>
      
    </div>

  </div>
</div>



<%= javascript_tag do %>
  $(document).ready(function(){
    $("#delete_button").attr('disabled', true);

    $("#delete_confirm").change(function(){
      if(this.value == 'delete') {
        $("#delete_button").attr('disabled', false);
      } else {
        $("#delete_button").attr('disabled', true);
      }
    });
    
    $("#delete_confirm").keyup(function(){
      if(this.value == 'delete') {
        $("#delete_button").attr('disabled', false);
      } else {
        $("#delete_button").attr('disabled', true);
      }
    });
    
  });

<% end %>