config/routes.rb
Rails.application.routes.draw do

  get 'welcome/index'

  devise_for :users, controllers: { registrations: "registrations" }

  resources :projects do
    resources :tickets
  end
  
  get '/projects/:id/new_associate', to: 'projects#new_associate'
  get 'index_tickets', to: 'projects#index_tickets'
  get '/projects/:id/quit', to: 'projects#quit'
  patch '/projects/:id/invite', to: 'projects#invite'
  patch '/projects/:id/change_owner', to: 'projects#change_owner'
  patch '/projects/:id/force_quit', to: 'projects#force_quit'
  
  

   root 'welcome#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>


<nav class="navbar navbar-default">
  <div class="container-fluid">
    
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Project manager", welcome_index_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "Browse", projects_path %></li>
      </ul>
      

      <ul class="nav navbar-nav navbar-right ">
        
        <% if user_signed_in? %>
          <li><li><%= link_to "My projects", projects_path(:private => true) %></li></li>
          <% l = Ticket.where(:user_id => current_user.email, :reported=>false).count %>
          <% if l>0 %>
            <% l = "(#{l} new)" %>
          <% else %>
            <% l = nil %>
          <% end %>
          <li><%= link_to "My tickets #{l}", controller: "projects", action: "index_tickets" %></li>
        <% end %>
        
        <% if user_signed_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
              <% if user_signed_in? %>
                <%= current_user.email %>
              <% end %>
  
            <span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">
                
                  <li><%= link_to 'Edit profile', edit_user_registration_path %></li>
                  <li><%= link_to "Logout", destroy_user_session_path, method: :delete  %></li>
      
            </ul>
          </li>
        
          <% else %>
          
            <li><%= link_to "Login", new_user_session_path %></li>
            <li>
            <div>
              
             
              
              <%= link_to "Sign up", new_user_registration_path, class: "btn btn-primary navbar-btn", role: "button" %>
              
            </div>
          </li>
          <% end %>
      

      </ul>
      
    </div>
  </div>
  
</nav>



<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>

<div class="container-fluid">
  
  <%= yield %>
  
</div>

<%= render 'cookies_eu/cookies_eu' %>

</body>
</html>